const{PART_POOLS:POOLS,PART_IDS:partIds,PRESTIGE_BASE,PRESTIGE_SCALE,PRESTIGE_BONUS,SAVE_KEY:KEY}=window.FaceConfig;
const{retrigger:trigger,scatter}=window.FaceEffects;
(()=>{'use strict';const S={economyVersion:2,impressions:0,dander:0,air:0,moisture:0,total:0,clickLevel:0,pupilLevel:0,secondEye:false,focus:0,browUnlocked:false,browLevel:0,secondBrow:false,lidsUnlocked:false,lashLevel:0,blinkAutoLevel:0,fatigue:0,noseUnlocked:false,airwayLevel:0,noseMoistureLevel:0,noseHairLevel:0,secondNostril:false,deepBreathLevel:0,mouthUnlocked:false,mouthAirLevel:0,mouthMoistureLevel:0,prestige:0,cosmetics:null,lastSaved:Date.now()},$=x=>document.getElementById(x),E={imp:$('imp'),ips:$('ips'),dan:$('dan'),eye1:$('eye1'),eye2:$('eye2'),brow1:$('brow1'),brow2:$('brow2'),ocular:$('ocular'),brows:$('brows'),lids:$('lids'),noseUpgrades:$('noseUpgrades'),mouthUpgrades:$('mouthUpgrades'),browSection:$('browSection'),browDesc:$('browDesc'),notice:$('notice'),save:$('save'),floats:$('floats')};let streak=0,lastClick=0,lastFrame=performance.now(),lastUiFrame=0,autoBlinkClock=0,browPulseClock=0,nosePulseClock=0,moisturePulseClock=0,deepBreathClock=0,mouthPulseClock=0,blinkTimer=0,gameSpeed=1;
const randomCosmetics=()=>Object.fromEntries(Object.entries(POOLS).map(([key,[,count]])=>[key,Math.floor(Math.random()*count)]));
const partPath=key=>{const [code]=POOLS[key];return `assets/parts/${code}/${code}_${String(S.cosmetics[key]).padStart(5,'0')}.png`};
const globalMult=()=>1+(S.prestige||0)*PRESTIGE_BONUS,prestigeRequirement=()=>PRESTIGE_BASE*PRESTIGE_SCALE**(S.prestige||0);
const moistureMultiplier=()=>1+Math.min(1,Math.log10(1+(S.moisture||0))*.08),eyeMultiplier=()=>globalMult()*moistureMultiplier(),clickBase=()=>(1+S.clickLevel)*eyeMultiplier(),fatigueEfficiency=()=>1-Math.min(1,S.fatigue||0)*.65,focusMax=()=>1+S.focus*.25,focusMul=()=>S.secondEye?1+(focusMax()-1)*Math.min(streak,10)/10:1,pupilRate=()=>S.pupilLevel*(1+S.clickLevel*.08)*(S.secondEye?2:1)*eyeMultiplier(),danderRate=()=>S.browUnlocked?S.browLevel*(S.secondBrow?2:1)*globalMult():0,expression=()=>S.secondBrow?pupilRate()*.1:0,blinkYield=()=>Math.max(1,S.lashLevel)*globalMult(),blinkInterval=()=>8/(1+(S.blinkAutoLevel||0)*.35),blinkDanderRate=()=>S.blinkAutoLevel?blinkYield()/blinkInterval():0,noseAirRate=()=>S.noseUnlocked?Math.max(1,S.airwayLevel)*(S.secondNostril?2:1)*(1+(S.deepBreathLevel||0)*.25)*globalMult():0,noseMoistureRate=()=>S.noseUnlocked?Math.max(1,S.noseMoistureLevel)*globalMult():0,mouthAirRate=()=>S.mouthUnlocked?Math.max(1,S.mouthAirLevel)*2*globalMult():0,mouthMoistureRate=()=>S.mouthUnlocked?Math.max(1,S.mouthMoistureLevel)*2*globalMult():0,totalAirRate=()=>noseAirRate()+mouthAirRate(),totalMoistureRate=()=>noseMoistureRate()+mouthMoistureRate(),pluckYield=()=>Math.max(1,S.noseHairLevel)*3*globalMult(),exhaleYield=()=>Math.max(1,S.mouthAirLevel)*4*globalMult(),fmt=n=>n<1000?(n<10?n.toFixed(1).replace('.0',''):Math.floor(n).toLocaleString()):(()=>{let v=n,i=-1,u=['K','M','B','T'];while(v>=1000&&i<u.length-1){v/=1000;i++}return v.toFixed(v<10?2:1)+u[i]})();
const U=[
{id:'click',area:'ocular',name:'Sharper Recall',cur:'impressions',cost:()=>10*1.15**S.clickLevel,detail:()=>`Manual observation +${fmt(clickBase())} · Level ${S.clickLevel}`,buy:()=>S.clickLevel++},
{id:'pupil',area:'ocular',name:'Pupil Dilation',cur:'impressions',cost:()=>25*1.15**S.pupilLevel,detail:()=>`Automated observation ${fmt(pupilRate())}/sec · Level ${S.pupilLevel}`,buy:()=>{S.pupilLevel++;flash('The pupil begins working without instruction.')}},
{id:'secondEye',area:'ocular',name:'Record Second Eye',cur:'impressions',cost:()=>175,hide:()=>S.secondEye,detail:()=>`Completes the pair and enables Focus.`,buy:()=>{S.secondEye=true;splash('SECOND EYE');flash('Binocular record complete. Focus is now possible.')}},
{id:'focus',area:'ocular',name:'Sustain Focus',cur:'impressions',cost:()=>90*1.35**S.focus,hide:()=>!S.secondEye,detail:()=>`Rapid clicks build to ×${fmt(focusMax())} · Level ${S.focus}`,buy:()=>S.focus++},
{id:'browUnlock',area:'ocular',name:'Record Eyebrow',cur:'impressions',cost:()=>500,hide:()=>S.browUnlocked,detail:()=>`Unlocks passive pooled Dander.`,buy:()=>{S.browUnlocked=true;S.browLevel=Math.max(1,S.browLevel);splash('EYEBROW');flash('A coarse line resolves above the eye.')}},
{id:'browLevel',area:'brows',name:'Follicle Density',cur:'dander',cost:()=>8*1.15**S.browLevel,detail:()=>`${fmt(danderRate())} Dander/sec · Level ${S.browLevel}`,buy:()=>S.browLevel++},
{id:'secondBrow',area:'brows',name:'Record Second Eyebrow',cur:'dander',cost:()=>75,hide:()=>S.secondBrow,detail:()=>`Expression converts 10% of automated Impressions into Dander.`,buy:()=>{S.secondBrow=true;splash('EXPRESSION');flash('The expression is now approximately symmetrical.')}},
{id:'lidUnlock',area:'brows',name:'Record Eyelids',cur:'dander',cost:()=>180,hide:()=>!S.browUnlocked||S.lidsUnlocked,detail:()=>`Unlocks blinking, fatigue cleansing, and pooled Dander.`,buy:()=>{S.lidsUnlocked=true;S.lashLevel=Math.max(1,S.lashLevel);splash('EYELIDS');flash('The subject can now interrupt observation.')}},
{id:'lashLevel',area:'lids',name:'Lash Density',cur:'dander',cost:()=>35*1.2**Math.max(0,S.lashLevel-1),hide:()=>!S.lidsUnlocked,detail:()=>`Each blink sheds ${fmt(blinkYield())} pooled Dander · Level ${S.lashLevel}`,buy:()=>S.lashLevel++},
{id:'blinkAuto',area:'lids',name:'Blink Reflex',cur:'dander',cost:()=>80*1.3**S.blinkAutoLevel,hide:()=>!S.lidsUnlocked,detail:()=>S.blinkAutoLevel?`Automatic blink every ${blinkInterval().toFixed(1)} sec · ${fmt(blinkDanderRate())} Dander/sec · Level ${S.blinkAutoLevel}`:`Automates blinking independently.`,buy:()=>{S.blinkAutoLevel++;autoBlinkClock=0;flash('The lids acquire an involuntary rhythm.')}},
{id:'noseUnlock',area:'lids',name:'Record Nose',cur:'dander',cost:()=>420,hide:()=>!S.lidsUnlocked||S.noseUnlocked,detail:()=>`Unlocks one nostril, passive Air, Moisture, and active hair pulling.`,buy:()=>{S.noseUnlocked=true;S.airwayLevel=Math.max(1,S.airwayLevel);S.noseMoistureLevel=Math.max(1,S.noseMoistureLevel);S.noseHairLevel=Math.max(1,S.noseHairLevel);splash('NOSE');flash('A single airway opens. Something inside it is productive.')}},
{id:'airway',area:'noseUpgrades',name:'Airway Patency',cur:'air',cost:()=>15*1.18**Math.max(0,S.airwayLevel-1),hide:()=>!S.noseUnlocked,detail:()=>`${fmt(noseAirRate())} nasal Air/sec · Level ${S.airwayLevel}`,buy:()=>S.airwayLevel++},
{id:'boogie',area:'noseUpgrades',name:'Real Dripper',cur:'moisture',cost:()=>10*1.2**Math.max(0,S.noseMoistureLevel-1),hide:()=>!S.noseUnlocked,detail:()=>`${fmt(noseMoistureRate())} Moisture/sec · soft boogies included · Level ${S.noseMoistureLevel}`,buy:()=>S.noseMoistureLevel++},
{id:'noseHair',area:'noseUpgrades',name:'Coarse Follicles',cur:'dander',cost:()=>120*1.22**Math.max(0,S.noseHairLevel-1),hide:()=>!S.noseUnlocked,detail:()=>`Pulling yields ${fmt(pluckYield())} Dander · Level ${S.noseHairLevel}`,buy:()=>S.noseHairLevel++},
{id:'secondNostril',area:'noseUpgrades',name:'Record Second Nostril',cur:'air',cost:()=>300,hide:()=>!S.noseUnlocked||S.secondNostril,detail:()=>`Doubles steady Air and unlocks Deep Breath.`,buy:()=>{S.secondNostril=true;splash('SECOND NOSTRIL');flash('The airway is bilateral. Deep breathing is now possible.')}},
{id:'deepBreath',area:'noseUpgrades',name:'Deep Breath',cur:'air',cost:()=>220*1.35**S.deepBreathLevel,hide:()=>!S.secondNostril,detail:()=>`+25% nasal Air per level and a six-second intake pulse · Level ${S.deepBreathLevel}`,buy:()=>S.deepBreathLevel++},
{id:'mouthUnlock',area:'noseUpgrades',name:'Record Mouth',cur:'moisture',cost:()=>250,hide:()=>!S.noseUnlocked||S.mouthUnlocked,detail:()=>`Unlocks oral Air at 2× baseline, saliva, and active exhaling.`,buy:()=>{S.mouthUnlocked=true;S.mouthAirLevel=Math.max(1,S.mouthAirLevel);S.mouthMoistureLevel=Math.max(1,S.mouthMoistureLevel);splash('MOUTH');flash('The mouth opens. The economy is now circular.')}},
{id:'oralAir',area:'mouthUpgrades',name:'Oral Airflow',cur:'air',cost:()=>45*1.2**Math.max(0,S.mouthAirLevel-1),hide:()=>!S.mouthUnlocked,detail:()=>`${fmt(mouthAirRate())} oral Air/sec · 2× baseline · Level ${S.mouthAirLevel}`,buy:()=>S.mouthAirLevel++},
{id:'saliva',area:'mouthUpgrades',name:'Salivary Response',cur:'moisture',cost:()=>35*1.2**Math.max(0,S.mouthMoistureLevel-1),hide:()=>!S.mouthUnlocked,detail:()=>`${fmt(mouthMoistureRate())} oral Moisture/sec · Level ${S.mouthMoistureLevel}`,buy:()=>S.mouthMoistureLevel++}];
function observe(e){let now=performance.now();streak=now-lastClick<700?Math.min(10,streak+1):1;lastClick=now;let n=clickBase()*focusMul()*fatigueEfficiency();S.impressions+=n;S.total+=n;if(S.lidsUnlocked)S.fatigue=Math.min(1,(S.fatigue||0)+.035);let r=$('face').getBoundingClientRect(),x=document.createElement('b');x.className='float'+(streak>=8?' combo':'');x.textContent='+'+fmt(n);x.style.left=e.clientX-r.left+'px';x.style.top=e.clientY-r.top+'px';E.floats.append(x);setTimeout(()=>x.remove(),900);for(let i=0;i<Math.min(11,3+streak);i++){let p=document.createElement('i');p.className='particle';p.style.left=e.clientX-r.left+'px';p.style.top=e.clientY-r.top+'px';p.style.setProperty('--dx',(Math.random()-.5)*75+'px');p.style.setProperty('--dy',(-15-Math.random()*55)+'px');p.style.setProperty('--rot',Math.random()*180+'deg');if(i%3===0)p.style.background='var(--red)';$('particles').append(p);setTimeout(()=>p.remove(),500)}trigger(e.currentTarget,'hit');trigger(E.imp,'stat-punch');if(streak===10)trigger(document.querySelector('.app'),'shake');render()}
function blink(manual=true){if(!S.lidsUnlocked)return;S.fatigue=0;S.dander+=blinkYield();let art=$('lidsArt'),face=$('face');clearTimeout(blinkTimer);face.classList.remove('blinking');art.classList.remove('hidden');void face.offsetWidth;face.classList.add('blinking');blinkTimer=setTimeout(()=>{face.classList.remove('blinking');art.classList.add('hidden')},650);trigger(E.dan,'stat-punch');if(manual)flash(`Blink complete. +${fmt(blinkYield())} pooled Dander; ocular fatigue cleared.`);render()}
function browPulse(){if(!S.browUnlocked||danderRate()<=0)return;let face=$('face');face.classList.toggle('double-brow',S.secondBrow);trigger(face,'brow-producing');let count=S.secondBrow?7:4;for(let i=0;i<count;i++){let p=document.createElement('i');p.className='dander-speck';p.style.left=(44+Math.random()*12)+'%';p.style.top=(25+Math.random()*4)+'%';p.style.setProperty('--drift',((Math.random()-.5)*42)+'px');$('particles').append(p);setTimeout(()=>p.remove(),850)}trigger(E.dan,'stat-punch')}
function pluckNoseHair(){if(!S.noseUnlocked)return;let amount=pluckYield();S.dander+=amount;trigger($('face'),'nose-plucking');trigger(E.dan,'stat-punch');scatter($('particles'),{count:6,x:50,y:53,spread:55});flash(`A hair comes free. +${fmt(amount)} pooled Dander.`);render()}
function noseBreath(deep=false){if(!S.noseUnlocked)return;trigger($('face'),deep?'deep-breath':'nose-breathing');if(deep){let bonus=noseAirRate();S.air+=bonus;trigger($('air'),'stat-punch')}}
function dripBoogie(){if(!S.noseUnlocked)return;let p=document.createElement('i');p.className='boogie-drop';p.style.left=(49+Math.random()*2)+'%';p.style.top='54%';p.style.setProperty('--drift',((Math.random()-.5)*18)+'px');$('particles').append(p);setTimeout(()=>p.remove(),1150);trigger($('moisture'),'stat-punch')}
function exhale(){if(!S.mouthUnlocked)return;let amount=exhaleYield();S.air+=amount;trigger($('face'),'mouth-exhaling');trigger($('air'),'stat-punch');flash(`Oral exhalation: +${fmt(amount)} Air.`);render()}
function mouthMoisturePulse(){if(!S.mouthUnlocked)return;trigger($('face'),'mouth-moistening');let p=document.createElement('i');p.className='moisture-drop';p.style.left=(49+Math.random()*2)+'%';p.style.top='66%';p.style.setProperty('--drift',((Math.random()-.5)*16)+'px');$('particles').append(p);setTimeout(()=>p.remove(),1000);trigger($('moisture'),'stat-punch')}
function splash(t){$('splashText').textContent=t;trigger($('splash'),'show');trigger(document.querySelector('.app'),'shake')}
function applyCosmetics(){if(!S.cosmetics)S.cosmetics=randomCosmetics();Object.keys(POOLS).forEach((key,index)=>{let el=$(partIds[key]);el.src=partPath(key);el.style.setProperty('--part-index',index)})}
function rerollCosmetics(){let previous=S.cosmetics||{},next=randomCosmetics();Object.keys(POOLS).forEach(key=>{if(next[key]===previous[key])next[key]=(next[key]+1)%POOLS[key][1]});S.cosmetics=next;trigger($('face'),'rerolling');applyCosmetics()}
function prestige(){if(S.total<prestigeRequirement())return;if(!confirm('Reconstitute the subject? All resources and upgrades will reset. The global production bonus and new facial fragments are permanent.'))return;S.prestige=(S.prestige||0)+1;Object.assign(S,{economyVersion:2,impressions:0,dander:0,air:0,moisture:0,total:0,clickLevel:0,pupilLevel:0,secondEye:false,focus:0,browUnlocked:false,browLevel:0,secondBrow:false,lidsUnlocked:false,lashLevel:0,blinkAutoLevel:0,fatigue:0,noseUnlocked:false,airwayLevel:0,noseMoistureLevel:0,noseHairLevel:0,secondNostril:false,deepBreathLevel:0,mouthUnlocked:false,mouthAirLevel:0,mouthMoistureLevel:0});streak=0;autoBlinkClock=0;browPulseClock=0;nosePulseClock=0;moisturePulseClock=0;deepBreathClock=0;mouthPulseClock=0;rerollCosmetics();splash(`REVISION ${S.prestige}`);flash('The prior subject has been discarded. This arrangement produces more efficiently.');save();render()}
function flash(t){E.notice.textContent=t;setTimeout(()=>E.notice.textContent='The record is incomplete.',4000)}
function buy(u){let c=Math.ceil(u.cost()),balance=S[u.cur]||0;if(balance<c)return;S[u.cur]=balance-c;let b=document.querySelector(`[data-u="${u.id}"]`);if(b)trigger(b,'purchase-hit');u.buy();save();render()}
function renderUpgrades(){
 U.forEach(u=>{
  let b=document.querySelector(`[data-u="${u.id}"]`);
  if(u.hide&&u.hide()){b?.remove();return}
  if(!b){
   b=document.createElement('button');b.className='upgrade';b.dataset.u=u.id;
   let name=document.createElement('span'),cost=document.createElement('span'),detail=document.createElement('span');name.className='upgrade-name';cost.className='cost';detail.className='detail';b.replaceChildren(name,cost,detail);b._view={name,cost,detail};
   b.onclick=()=>buy(u);b.onpointerdown=()=>b.classList.add('pressed');b.onpointerup=b.onpointercancel=b.onpointerleave=()=>b.classList.remove('pressed');E[u.area].append(b)
  }
  let c=Math.ceil(u.cost()),balance=S[u.cur]||0,codes={impressions:'IMP',dander:'DAN',air:'AIR',moisture:'MOI'},code=codes[u.cur]||u.cur.toUpperCase(),afford=Math.min(100,balance/c*100),ready=balance>=c;
  let nameText=u.name,costText=`${fmt(c)} ${code}`,detailText=u.detail(),label=`${u.name}, costs ${fmt(c)} ${code}${ready?', available':', unavailable'}`;
  if(b._view.name.textContent!==nameText)b._view.name.textContent=nameText;if(b._view.cost.textContent!==costText)b._view.cost.textContent=costText;if(b._view.detail.textContent!==detailText)b._view.detail.textContent=detailText;
  if(b.disabled===ready)b.disabled=!ready;b.classList.toggle('affordable',ready);b.style.setProperty('--afford',afford.toFixed(1)+'%');if(b.getAttribute('aria-label')!==label)b.setAttribute('aria-label',label)
 })
}
function render(){
 E.imp.textContent=fmt(S.impressions);E.ips.textContent=fmt(pupilRate());E.dan.textContent=fmt(S.dander);
 $('air').textContent=fmt(S.air||0);$('moisture').textContent=fmt(S.moisture||0);
 $('streakText').textContent='×'+focusMul().toFixed(2);$('streakFill').style.width=Math.min(100,streak*10)+'%';$('streakHud').classList.toggle('live',streak>0);$('streakHud').classList.toggle('hot',streak>=8);
 let fatigue=Math.round((S.fatigue||0)*100);$('fatigueText').textContent=fatigue+'%';$('fatigueFill').style.width=fatigue+'%';document.querySelector('.fatigue-hud').classList.toggle('danger',fatigue>=75);
 E.eye1.classList.toggle('auto',S.pupilLevel>0);E.eye2.classList.toggle('hidden',!S.secondEye);E.eye2.classList.toggle('auto',S.pupilLevel>0);E.eye2.disabled=!S.secondEye;
 E.brow1.classList.toggle('hidden',!S.browUnlocked);E.brow2.classList.toggle('hidden',!S.secondBrow);$('eyesArt').classList.toggle('single-part',!S.secondEye);$('pupilsArt').classList.toggle('single-part',!S.secondEye);$('lidsArt').classList.toggle('single-part',!S.secondEye);$('browsArt').classList.toggle('hidden',!S.browUnlocked);$('browsArt').classList.toggle('single-part',!S.secondBrow);$('pupilsArt').classList.toggle('hidden',S.pupilLevel<1);if(!$('face').classList.contains('blinking'))$('lidsArt').classList.add('hidden');
 $('blinkButton').classList.toggle('hidden',!S.lidsUnlocked);$('blinkYield').textContent=`+${fmt(blinkYield())} DANDER`;E.browSection.classList.toggle('locked',!S.browUnlocked);E.browDesc.textContent=S.browUnlocked?`Loose material accumulates at ${fmt(danderRate()+expression()+blinkDanderRate())} per second.`:'Insufficient visual material.';$('lidSection').classList.toggle('locked',!S.lidsUnlocked);$('lidDesc').textContent=S.lidsUnlocked?`Blinking clears fatigue and sheds pooled Dander${S.blinkAutoLevel?` at ${fmt(blinkDanderRate())} per second.`:'.'}`:'Blink response not yet recorded.';
 $('noseArt').classList.toggle('unprocessed',!S.noseUnlocked);$('noseButton').classList.toggle('hidden',!S.noseUnlocked);$('pluckYield').textContent=`+${fmt(pluckYield())} DANDER`;document.querySelector('.nose').classList.toggle('hidden',S.noseUnlocked);$('noseSection').classList.toggle('locked',!S.noseUnlocked);$('noseDesc').textContent=S.noseUnlocked?`${S.secondNostril?'Two nostrils':'One nostril'} produce ${fmt(noseAirRate())} Air/sec and ${fmt(noseMoistureRate())} Moisture/sec.`:'No airway has been entered into evidence.';
 $('mouthArt').classList.toggle('unprocessed',!S.mouthUnlocked);$('mouthButton').classList.toggle('hidden',!S.mouthUnlocked);$('exhaleYield').textContent=`+${fmt(exhaleYield())} AIR`;$('mouthSection').classList.toggle('locked',!S.mouthUnlocked);$('mouthDesc').textContent=S.mouthUnlocked?`The mouth produces ${fmt(mouthAirRate())} Air/sec and ${fmt(mouthMoistureRate())} Moisture/sec. Stored Moisture multiplies eye output by ×${moistureMultiplier().toFixed(2)}.`:'The mouth remains outside the present record.';
 let req=prestigeRequirement(),ready=S.total>=req;$('prestigeButton').disabled=!ready;$('prestigeRequirement').textContent=ready?'RECONSTITUTION READY':`${fmt(Math.max(0,req-S.total))} IMP REMAIN`;$('prestigeLevel').textContent=`REVISION ${S.prestige||0} · ×${globalMult().toFixed(2)} GLOBAL`;renderUpgrades()
}
function save(){S.lastSaved=Date.now();localStorage.setItem(KEY,JSON.stringify(S));E.save.textContent='RECORD SAVED';setTimeout(()=>E.save.textContent='LOCAL RECORD ACTIVE',1000)}
async function exportSave(){save();let payload=JSON.stringify({game:'FACE',format:1,exportedAt:new Date().toISOString(),state:S},null,2),file=new File([payload],`face-save-${new Date().toISOString().slice(0,10)}.json`,{type:'application/json'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({title:'FACE save record',files:[file]});flash('Save record shared.');return}}catch(e){if(e.name==='AbortError')return}let url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);flash('Save record exported.')}
async function importSave(file){if(!file)return;try{let parsed=JSON.parse(await file.text()),state=parsed.state||parsed;if(!state||typeof state!=='object'||typeof state.impressions!=='number'||typeof state.total!=='number')throw new Error('Invalid FACE save');localStorage.setItem(KEY,JSON.stringify(state));location.reload()}catch(e){flash('Import rejected: this is not a valid FACE save.')}finally{$('saveFile').value=''}}
function load(){try{let saved=JSON.parse(localStorage.getItem(KEY));if(saved){let legacy=!saved.economyVersion||saved.economyVersion<2;Object.assign(S,saved);if(legacy){S.dander=(S.dander||0)+(saved.silverDander||0);S.moisture=(S.moisture||0)+(saved.boogies||0);S.noseMoistureLevel=saved.noseMoistureLevel||saved.boogieLevel||0;S.economyVersion=2;delete S.silverDander;delete S.boogies;delete S.boogieLevel;flash('Economy consolidated: Silver Dander became Dander; Soft Boogies became Moisture.')}['prestige','lashLevel','blinkAutoLevel','fatigue','air','moisture','airwayLevel','noseMoistureLevel','noseHairLevel','deepBreathLevel','mouthAirLevel','mouthMoistureLevel'].forEach(k=>S[k]=S[k]||0);let sec=Math.min(28800,Math.max(0,(Date.now()-S.lastSaved)/1000));if(sec>5){let i=pupilRate()*sec*.5,d=(danderRate()+expression()+blinkDanderRate())*sec*.5,a=totalAirRate()*sec*.5,m=totalMoistureRate()*sec*.5;S.impressions+=i;S.total+=i;S.dander+=d;S.air+=a;S.moisture+=m;flash(`Offline record: +${fmt(i)} impressions, +${fmt(d)} dander, +${fmt(a)} air, +${fmt(m)} moisture.`)}}}catch(e){localStorage.removeItem(KEY)}if(!S.cosmetics)S.cosmetics=randomCosmetics();applyCosmetics()}
function toggleDev(show){$('devPanel').classList.toggle('hidden',show===undefined?!$('devPanel').classList.contains('hidden'):!show)}
function devAction(action){if(action==='imp'){S.impressions+=1000;S.total+=1000}else if(action==='dan')S.dander+=250;else if(action==='air')S.air=(S.air||0)+250;else if(action==='moisture')S.moisture=(S.moisture||0)+250;else if(action==='fatigue')S.fatigue=0;else if(action==='prestige'){let grant=Math.max(0,prestigeRequirement()-S.total);S.total+=grant;S.impressions+=grant}else if(action==='speed'){gameSpeed=gameSpeed===1?5:gameSpeed===5?10:1;$('speedButton').textContent=`SPEED ×${gameSpeed}`}render()}
function loop(t){
 let realDt=Math.min(1,(t-lastFrame)/1000),dt=realDt*gameSpeed;lastFrame=t;
 let i=pupilRate()*dt;S.impressions+=i;S.total+=i;S.dander+=(danderRate()+expression())*dt;S.air+=totalAirRate()*dt;S.moisture+=totalMoistureRate()*dt;
 if(danderRate()>0){browPulseClock+=realDt;if(browPulseClock>=Math.max(.35,1/gameSpeed)){browPulseClock=0;browPulse()}}else browPulseClock=0;
 if(S.noseUnlocked){nosePulseClock+=realDt;moisturePulseClock+=realDt;if(nosePulseClock>=Math.max(.38,1.2/gameSpeed)){nosePulseClock=0;noseBreath(false)}if(moisturePulseClock>=Math.max(.55,1.5/gameSpeed)){moisturePulseClock=0;dripBoogie()}}
 if(S.mouthUnlocked){mouthPulseClock+=realDt;if(mouthPulseClock>=Math.max(.55,1.35/gameSpeed)){mouthPulseClock=0;mouthMoisturePulse()}}
 if(S.secondNostril){deepBreathClock+=dt;if(deepBreathClock>=6){deepBreathClock%=6;noseBreath(true)}}
 if(S.blinkAutoLevel){autoBlinkClock+=dt;if(autoBlinkClock>=blinkInterval()){autoBlinkClock%=blinkInterval();blink(false)}}
 if(t-lastClick>800)streak=Math.max(0,streak-dt*2);if(t-lastUiFrame>=100){render();lastUiFrame=t}requestAnimationFrame(loop)
}
function setMobileView(view,updateHash=true){let upgrades=view==='upgrades';document.body.classList.toggle('show-upgrades',upgrades);document.querySelectorAll('.mobile-nav button').forEach(x=>{let active=x.dataset.view===(upgrades?'upgrades':'face');x.classList.toggle('active',active);x.setAttribute('aria-pressed',active)});if(updateHash&&matchMedia('(max-width:820px)').matches)history.replaceState(null,'','#'+(upgrades?'upgrades':'face'))}
E.eye1.onclick=observe;E.eye2.onclick=observe;$('blinkButton').onclick=()=>blink(true);$('noseButton').onclick=pluckNoseHair;$('mouthButton').onclick=exhale;$('prestigeButton').onclick=prestige;$('devToggle').onclick=()=>toggleDev();$('devClose').onclick=()=>toggleDev(false);$('exportSave').onclick=exportSave;$('importSave').onclick=()=>$('saveFile').click();$('saveFile').onchange=e=>importSave(e.target.files[0]);document.querySelectorAll('.mobile-nav button').forEach(b=>b.onclick=()=>setMobileView(b.dataset.view));setMobileView(location.hash==='#upgrades'?'upgrades':'face',false);document.querySelectorAll('[data-dev]').forEach(b=>b.onclick=()=>devAction(b.dataset.dev));document.addEventListener('keydown',e=>{if(e.key==='`')toggleDev();if(e.key.toLowerCase()==='b'&&S.lidsUnlocked)blink(true);if(e.key.toLowerCase()==='n'&&S.noseUnlocked)pluckNoseHair();if(e.key.toLowerCase()==='m'&&S.mouthUnlocked)exhale()});$('reset').onclick=()=>{if(confirm('Destroy this composite record and all progress?')){localStorage.removeItem(KEY);location.reload()}};document.addEventListener('visibilitychange',()=>document.hidden&&save());addEventListener('beforeunload',save);setInterval(save,15000);if('serviceWorker'in navigator){navigator.serviceWorker.getRegistrations().then(registrations=>registrations.forEach(registration=>registration.unregister()));if('caches'in window)caches.keys().then(keys=>keys.filter(key=>key.startsWith('face-shell-')).forEach(key=>caches.delete(key)))}load();render();requestAnimationFrame(loop)})();
